name: Test with trezor-user-env
on:
  workflow_call:
    inputs:
      methods:
        description: "List of methods to include in tests (example applySettings,applyFlags,getFeatures)"
        type: "string"
        required: false
      test-pattern:
        description: "Test pattern to use (e.g. `init` or `methods`)"
        type: "string"
        required: true

jobs:
  test-nodejs:
    name: Test NodeJS (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: "**/yarn.lock"
    - run: yarn install
    - run: ./tests/run.sh -s 'yarn test:integration ${{ inputs.test-pattern }}' -i '${{ inputs.methods }}'

  test-methods-karma:
    name: Test Karma (${{ matrix.node-version }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: "**/yarn.lock"
    - run: yarn install
    - name: Retrieve build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build
    # xvfb is required to run karma
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum ./tests/run.sh -s 'yarn test:karma:production ${{ inputs.test-pattern }}' -i '${{ inputs.methods }}'
